### ISSUE TITLE
[FR] Green fix DVD over RGB like modbo 

### ISSUE THREAD

**Issue by L10N37** [ps2homebrew/wLaunchELF#103]
### Checks

- [ ] I have checked existing feature requests for duplicates and found none

### Describe the FR

DVDs play in green over RGB

### Describe the solution you'd like

can this be implemented ?

**Comment by AKuHAK** [comment]
Not quite sure how its related t wlauchelf. Install unnoficial dvd player RPC 3.11 on memory card.

**Comment by L10N37** [comment]
Thank you
