### ISSUE TITLE
OPL gets updated same day?

### ISSUE THREAD

**Issue by JMaxxL** [ps2homebrew/wLaunchELF#112]
### Checks

- [X] I have checked existing feature requests for duplicates and found none

### Describe the FR

seems you update your release every week nice !

### Describe the solution you'd like

what is the DVR for

### Describe alternatives you've considered

is it possible to remove the 'HOST' like the 4.43 dose in wLaunch.ELF dose in their NO_NETWORK release & their exFAT release dose ?

### Additional context

what is the DVR for? id love to take advantage of it...  I notice its updated same day as OPL im so interested in PS2 homebrew I have a SATA adaptered OEM network card, but really am interested in going compact flash to IDE route next.

![wDefault 4 43_isr](https://github.com/ps2homebrew/wLaunchELF/assets/78325531/6ac630b6-6fc4-4ac8-9401-a4343daf13eb)

see how this version has different variants the perfect version for me would be a FAT version yes FAT 4GB without a HOST plus a FAT32 version with only 1 USB lol I know weird right but that would make my life simplier Id love it if I could turn ON & OFF everything would be so cool.

**Comment by AKuHAK** [comment]
You post it in the wrong repo
