### ISSUE TITLE
PS2Net not working

### ISSUE THREAD

**Issue by Windows10User2** [ps2homebrew/wLaunchELF#121]
### Checks

- [ ] I have checked existing issues for duplicates and found none

### Describe the issue

Every time I run wLE 4.43a c46c88c's PS2Net, it always freezes at "Loading NetFS and FTP Server Modules...".

### Console model

SCPH-75004

**Comment by Windows10User2** [comment]
> @AKuHAK, @rickgaiser, @uyjulian, @fjtrujy, @israpps, i confirm this issue. Also, when I start wLE, I get this error:
> 
> ![IMG_20240130_235108](https://private-user-images.githubusercontent.com/59209149/301005763-bfdf2f92-e85d-4074-b4ee-82ac954e73ac.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MDQ4OTUsIm5iZiI6MTcwNjgwNDU5NSwicGF0aCI6Ii81OTIwOTE0OS8zMDEwMDU3NjMtYmZkZjJmOTItZTg1ZC00MDc0LWI0ZWUtODJhYzk1NGU3M2FjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE2MjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NTYyMTdiZjYzNTljMTQ1YmQ3Yzc2YTFkOTIwNDZhY2RiZGM2ZDllMDJmODU0OTA4YTJjYjZlNGNhYzE3ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_mxWRpDAnGmnzp7HHa1f9Snsui7RuhHWaBQdNw6H6w)

What does that have to do with [my](https://github.com/ps2homebrew/wLaunchELF/issues/121#issue-2101380242) issue? Anyway, how can wLE's language be changed and is it possible to change wLaunchELF_isr's?

**Comment by Windows10User2** [comment]
> @Windows10User2, read [this](https://sksapps.haldrie.com/tutorials/ps2/ule_noobie_guide/startup.html) and use [this](https://github.com/israpps/wLaunchELF_ISR/releases/tag/language-files).

Are english and spanish the only available languages? Why is the former even available when it already comes with wLaunchELF_isr? Also, does the original wLE have language packs, and if so, can they be used on wLaunchELF_isr?

**Comment by Windows10User2** [comment]
> > Are english and spanish the only available languages?
> 
> No, there are also [BRA](https://github.com/ps2homebrew/wLaunchELF/pull/106), [KOR](https://github.com/israpps/wLaunchELF_ISR/pull/31) and some others [here](https://web.archive.org/web/20151105114358/http://psx-scene.com/forums/f113/release-thread-ulaunchelf-support-files-46447/).
> 
> > Why is the former even available when it already comes with wLaunchELF_isr?
> 
> It is used for translation into other languages.
> 
> > Also, does the original wLE have language packs, and if so, can they be used on wLaunchELF_isr?
> 
> Yes, but all new features will be in English.
> 
> @uyjulian, this issue is fixed in [Latest development build](https://github.com/ps2homebrew/wLaunchELF/releases/tag/latest). But my language pack ([RUS](https://github.com/ps2homebrew/wLaunchELF/files/14203024/RUS.zip)) still displays the same error as in the photo above, although it worked well before.

I find it odd the languages packs are only available on an inaccessible site (PSX Scene) and not in wLE's GitHub repository.

And no, [my](https://github.com/ps2homebrew/wLaunchELF/issues/121#issue-2101380242) issue isn't fixed. I still have it. Again, what does [your](https://github.com/ps2homebrew/wLaunchELF/issues/121#issuecomment-1918207666) issue have to do with [mine](https://github.com/ps2homebrew/wLaunchELF/issues/121#issue-2101380242)? Do wLE language packs work in wLE_isr?

**Comment by Windows10User2** [comment]
> > Are english and spanish the only available languages?
> 
> No, there are also [BRA](https://github.com/ps2homebrew/wLaunchELF/pull/106), [KOR](https://github.com/israpps/wLaunchELF_ISR/pull/31) and some others [here](https://web.archive.org/web/20151105114358/http://psx-scene.com/forums/f113/release-thread-ulaunchelf-support-files-46447/).
> 
> > Why is the former even available when it already comes with wLaunchELF_isr?
> 
> It is used for translation into other languages.
> 
> > Also, does the original wLE have language packs, and if so, can they be used on wLaunchELF_isr?
> 
> Yes, but all new features will be in English.
> 
> @AKuHAK, @uyjulian, this issue is fixed in [Latest development build](https://github.com/ps2homebrew/wLaunchELF/releases/tag/latest). But my language pack ([RUS](https://github.com/ps2homebrew/wLaunchELF/files/14203024/RUS.zip)) still displays the same error as in the photo above, although it worked well before.

It's not fixed. I still have this issue.

**Comment by AKuHAK** [comment]
> Do wLE language packs work in wLE_isr?

https://github.com/israpps/wLaunchELF_ISR/issues

**Comment by Windows10User2** [comment]
> > Do wLE language packs work in wLE_isr?
> 
> https://github.com/israpps/wLaunchELF_ISR/issues

?



> > Do wLE language packs work in wLE_isr?
> 
> I already answered this question.
> 
> @AKuHAK, FTP is already fixed for me. But is it possible to fix [this](https://github.com/ps2homebrew/wLaunchELF/issues/121#issuecomment-1918207666) issue?

But not why they're only available on an inaccessible site (PSX Scene) and not in wLE's GitHub repository. Also, for me FTP isn't fixed. I find it this problem lasts since an old version released years ago. If you have that problem regarding a language pack, hoe can I be sure I won't have it (or another) if using one?

**Comment by Windows10User2** [comment]
> > Do wLE language packs work in wLE_isr?
> 
> https://github.com/israpps/wLaunchELF_ISR/issues

?

> > Do wLE language packs work in wLE_isr?
> 
> I already answered this question.
> 
> @AKuHAK, FTP is already fixed for me. But is it possible to fix [this](https://github.com/ps2homebrew/wLaunchELF/issues/121#issuecomment-1918207666) issue?

But not why did you bring [your](https://github.com/ps2homebrew/wLaunchELF/issues/121#issuecomment-1918207666) issue to here when it doesn't have to do with [my](https://github.com/ps2homebrew/wLaunchELF/issues/121#issue-2101380242) problem. Also, you didn't say why the language packs are only available in an inaccessible site (PSX Scene) and not in wLE's GitHub repository. If you have [that](https://github.com/ps2homebrew/wLaunchELF/issues/121#issuecomment-1918207666) problem regarding a language pack, how can I be sure I won't have it (or another) if using a non-english one like yours?

Again, FTP isn't fixed for me. I find it odd this problem lasts since a version was released years ago.

EDIT: I checked wLE 4.43a f213b31's PS2Net and it doesn't freeze at "Loading NetFS and FTP Server Modules..." but now FileZilla Client can't access the PS2. It says "Could not connect to server".
