### ISSUE TITLE
How could I generate a ELF file with lastest release?

### ISSUE THREAD

**Issue by awilliansd** [ps2homebrew/wLaunchELF#63]
In lastest release, it doesn't have elf release, just source code.

**Comment by AKuHAK** [comment]
https://github.com/ps2homebrew/wLaunchELF/releases/tag/latest

**Comment by awilliansd** [comment]
It's pre-releae, I want release boot.elf.

In this link: https://github.com/ps2homebrew/wLaunchELF/releases/tag/190107
