### ISSUE TITLE
[ISSUE]: Squares between LaunchELF

### ISSUE THREAD

**Issue by Haker120** [ps2homebrew/wLaunchELF#71]
### Checks

- [X] I have checked existing issues for duplicates and found none

### Describe the issue

Squares are shown as marks, I know I have screen from fork but identical issue exists with this official version. No matter settings saved or without loaded LAUNCHELF.CFG. When I'll find the time I'll replace pic with official version.
![137621923-d258a8a8-2bb6-44d2-91df-7975ca85cd07](https://user-images.githubusercontent.com/26009830/138740253-00e74d0c-9096-4acb-ae16-45bb29a3e622.jpg)

### Console model

39004/50004/70004/77004/90004

**Comment by J013k** [comment]
To my eyes it looks more than a corrupted font. ;)

![https://i.postimg.cc/7ZMLVTtC/to.png](https://i.postimg.cc/7ZMLVTtC/to.png)

Anyway, I have the same problem.

**Comment by sl1pkn07** [comment]
i□unicode

same here. latest build from git

greetings

**Comment by israpps** [comment]
this is caused by the text encoding of `filer.c` (or `main.c`, can't remember)
