### ISSUE TITLE
[FR] Support for exFAT

### ISSUE THREAD

**Issue by Haker120** [ps2homebrew/wLaunchELF#80]
### Checks

- [x] I have checked existing feature requests for duplicates and found none

### Describe the FR

Just simple as that, to add support for exFAT formatted USB devices since OPL got it. 

### Describe the solution you'd like

Just for wLE to correctly detect exFAT USB device and support all available operations as for FAT32.

**Comment by AKuHAK** [comment]
fixed in #81
