### ISSUE TITLE
[ISSUE]: wlaunchelf does not copy ELF files to memory card and does not open them

### ISSUE THREAD

**Issue by derkaiser05** [ps2homebrew/wLaunchELF#91]
### Checks

- [X] I have checked existing issues for duplicates and found none

### Describe the issue

On the commit 3974981 wlaunchelf does not copy ELF files from USB to memory card and does not open ELF files from memory card, gives error. Was working the copy and open ELF files on commit bb89871

### Console model

SCPH-75001

**Comment by derkaiser05** [comment]
On the commit 395b72a the problem continues. Shows that ELF files are not ELF files when try open them from memory card.

**Comment by Haker120** [comment]
Same issue here with commit 395b72a1ced0cfec1b15f33275daff1baeaae8f2.

**Comment by derkaiser05** [comment]
> Same issue here with commit [395b72a](https://github.com/ps2homebrew/wLaunchELF/commit/395b72a1ced0cfec1b15f33275daff1baeaae8f2). More of this, it killed my OpenTuna installation.

When I tried to copy save game from memory card to USB HD, it corrupted HD. I had to format. I use EXFAT format.

**Comment by derkaiser05** [comment]
On the commit 0dcea7d the issues continues. Shows that ELF files are not ELF files when try open them from memory card, does not copy and paste files. Again I had to format the HD, because when trying to copy and paste files, wlaunchelf crashes and corrupts the HD.
